= Rząd londyński i Polskie Państwo Podziemne.
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:imagesdir: obrazki
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Przekroczenie granic.

=== Data.
W nocy z *17* na *18* *września 1939* r. władze Rzeczpospolitej przekroczyły granicę Rumunii. Liczyły na to, że przedostaną się do Francji, by kontynuować wojnę z Niemcami. Tak się nie stało.

=== Kto przekroczył.
*Prezydent Ignacy Mościcki*, *członkowie rządu*, *naczelny wódz* oraz liczni żołnierze zostali internowani przez Rumunów.

NOTE: Aby umożliwić powołanie nowych władz państwa, we *wrześniu 1939* r. prezydent i rząd podali się do dymisji. Prezydent wskazał swojego następcę, *Władysława Raczkiewicza*, który przebywał we Francji.

== Władysław Sikorski
. Piłsudczyków obwiniano o klęskę, dlatego premierem został ich przeciwnik.
. W *październiku 1939* r. utworzył on we Francji Rząd Rzeczpospolitej Polskiej na uchodźstwie, do którego weszli zarówno piłsudczycy, jak i politycy wrogiej sanacji.
. Objął funkcję *naczelnego wodza* i przystąpił do tworzenia *Polskich Sił Zbrojnych na Zachodzie*
. Uważał porozumienie ze związkiem radzieckim za konieczność, AK miała wraz z Armią Czerwoną pokonać Niemców i wkroczyć do kraju.
. Domagał się uwolnienia Polaków przetrzymywanych w sowieckich więzieniach i łagrach.

== Rząd londyński
. W *czerwcu 1940* tuż przed kapitulacją Francji, rząd znalazł schronienie w *Londynie* - stąd pochodzi jego nazwa *rząd londyński*, czyli *polski rząd emigracyjny*.
. Na Wyspy Brytyjskie przedostało się ok. 27 tysięcy polskich żołnierzy.

== Polityka zagranicznego rządu londyńskiego

=== Tezy polskiej polityki zagranicznej:
. Polska *będzie kontynuować* wojnę z Niemcami u boku Wielkiej Brytanii.
. Polska jest w stanie wojny z ZSRR.
. Rząd nie uznaje zaboru wschodniej części Polski ani aneksji państw bałtyckich przez ZSRR.

IMPORTANT: Sytuacja polaków skomplikowała się po napaści Niemiec na ZSRR (1941). Stalin został sojusznikiem Brytyjczyków, którzy naciskali na rząd londyński, by nawiązał stosunki z sowieckim dyktatorem w celu wspólnej walki przeciwko Trzeciej Rzeszy.

IMPORTANT: Niemcy zaatakowały ZSRR 22 czerwca 1942 roku.

== Układ Majski.
. W *lipcu 1941 r.* Polska i ZSRR podpisały układ *Sikorski-Majski*

TIP: Iwan Majski był radzieckim ambasadorem w Londynie.

=== Na jego mocy:
. ZSRR uznał, że traktaty sowiecko-niemieckie dotyczące zmiany polskich granic (pakt Ribbentrop-Mołotow) utraciły swą moc.
. Polska i ZSRR przywróciły stosunki dyplomatyczne (co ze strony Polski oznaczało zakończenie wojny z ZSRR).
. Strona radziecka zgodziła się na "amnestię" dla więzionych obywateli polski i utworzenie *Armii Polskie w ZSRR*podległej generałowi sikorskiemu*.

=== Armia Polska w ZSRR.
. Jej dowódcą został *generał Władysław Anders*, wcześniej więziony w Moskwie.
. Okazało się, ze wśród zwolnionych brakuje ok. 14 tysięcy oficerów wziętych do niewoli w 1939 r. (i zamordowanych m.in. w Katyniu). Stalin tłumaczył, że zapewne uciekli do Mandżurii i tam się odnajdą.

== Siły zbrojne.

=== Najważniejsze
* *Związek Walki Zbrojnej* (ZWZ) - przekształcone w *Armię Krajową* (AK)

=== Poza AK:
* *AL* (Armia Ludowa)
* *BCh* (Bataliony Chłopskie)

== Formy oporu:
Z początku AK rzadko organizowała akcje zbrojne, gdyż prowadziły one do okrutnych represji - hitlerowcy rozstrzeliwali kilkudziesięciu Polaków za każdego zabitego niemca. Skupiała się na innych formach oporu.

=== Propaganda.
Narzędziami propagandy były ulotki, podziemna prasa, hasła na murach itp. Służyła budzeniu nadziei, a także informowała społeczeństwo o sytuacji w kraju i na froncie.

=== Mały sabotaż.
Polegał na działaniach szkodzących wrogowi bez podejmowania walki zbrojnej - takich jak zrywanie hitlerowskich flag, malowanie na murach polskich haseł, zniszczenie niemieckich wystaw.

NOTE: Mały sabotaż prowadziła przede wszystkim młodzież z konspiracyjnego harcerstwa o nazwie *Szare Szeregi*.

=== Wywiad.
Zdobywał między innymi informacje o planowanym ataku Niemiec na ZSRR (Stalin je zlekceważył), dostarczył też na Zachód niewybuch rakiety V-2. Dzięki danym zdobytych przez wywiad AK lotnictwo alianckie zbombardowało fabrykę tych rakiet.

=== Działalność dywersyjna.
Pod *koniec 1942 roku* AK nosiła *działalność dywersyjną*: wykolejała transporty wojskowe przeznaczone na front wschodni, wysadzała mosty, odbijała więźniów. Straty zadane Niemcom były bardzo duże - wśród nich ponad 730 wykolejonych pociągów i przeszło 4 tysiące zniszczonych pojazdów wojskowych. Jednak w akcjach AK zginęło ponad 60 tysięcy jej żołnierzy.
