= Konkurs kuratoryjny z języka polskiego.
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:stem:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Synkretyzm rodzajowy.
. *Synkretyzmem* nazwiemy połączenie różnych, często rozbieżnych i sprzecznych poglądów; może to być wtedy wyznawanie zasad lub wierzeń obejmujących odległe od siebie elementy pozornie lub rzeczywiście wzajemnie sprzeczne.
. Synkretyzmem rodzajowym i gatunkowym będzie łączenie w jedną całość różnych gatunków literackich.
. *Przykład:* W literaturze romantycznej ballady pisał A. Mickiewicz, np w balladzie "Świtezianka" mamy narratora (epika), postacie (epika, dramat), nastrój grozy i tajemniczości, ożywiona przyroda(liryka).

== Średniówka.
Średniówka – punkt podziału, który rozbija wers na kilka (najczęściej: dwa tzw. hemistychy) części i zwykle występuje w wersach dłuższych niż ośmiosylabowe.

Miejsce średniówki w wersie zależne jest od granicy wyrazów i zestrojów akcentowych . Z reguły średniówka nie występuje w miejscach podziału zdaniowego , ponieważ byłoby to związane z silnym sygnałem intonacyjnym i tym samym spowodowałoby osłabienie klauzuli . *Średniówka występuje w wierszach sylabicznych , sylabotonicznych i tonicznych . Dla poezji polskiej charakterystyczna jest średniówka po piątej sylabie w jedenastozgłoskowcu i po siódmej sylabie w trzynastozgłoskowcu.*

== Przerzutnia.
. Przerzutnia może występować w tekście pisanym wierszem. Przerzutnia według najprostszej definicji to przesunięcie zakończenia zdania (wyrazu lub grupy wyrazów) do następnego wersu. Zjawisko przerzutni jest związane z intonacją wypowiedzi. Przerzutnia polega na rozbieżności między intonacją zdaniową i a podziałem wersowym (struktura składniowa i wersowa nie pokrywają się). 

. Efektem przerzutni jest rozbicie struktury składniowej. Przerzutnię można zaliczyć do składniowych środków stylistycznych. Pierwszym polskim twórcą, który szeroko stosował przerzutnię w utworach poetyckich był Jan Kochanowski. 
. *Funkcje:* przerzutnia poprzez swoiste wybicie odbiorcy z rytmu wiersza ma służyć *zwróceniu jego uwagi, wyeksponowaniu słów rozdzielonych zakończeniem wersu* (klauzulą). Przerzutnia *wpływa także na dynamikę wiersza, wzbogaca strukturę intonacyjną, zapobiega monotonii*.

== Wiersze
. Typy wierszy:
- stroficzny
- stychiczny (ciągły)
- biały (bez rymów)
- wolny

RYMY
.Rymy:
- dokładne
- niedokładne

. Rymy:
..  męskie / przykład: kot-płot
..  żeńskie / przykład: szafa-żyrafa

W męskich ( > 1,5 głoski)

W żeńskich ( 1,5 głoski)

. Układy rymów:
- parzyste/ aabb
- okalające/abba
- krzyżowane/abab

. Przykład rymów parzystych:
.. kot / a
.. płot / a
.. szafa / b
.. żyrafa / b

. Przykład rymów okalających:
.. kot / a
.. szafa / b
.. żyrafa / b
.. płot / a

. Przykład rymów krzyżowanych:
.. kot / a
.. szafa / b
.. płot / a
.. żyrafa / b

== Morał.
. *Morał* – uwaga, nauka umoralniająca; puenta końcowa o charakterze pouczającym, *objaśniająca symbolikę zdarzeń przedstawionych w utworze literackim, zwykle w bajce*. Ma postać zwięzłego, abstrakcyjnego sądu, zakazu lub nakazu.

== Epizod.
. *Epizod* - zdarzenie, sytuacja występująca w utworze fabularnym, *odgrywająca w nim drugorzędną rolę i tylko luźno połączona z przebiegiem akcji. Może pełnić funkcję tła*, służyć opóźnieniu akcji lub osłabieniu roli wątku w kompozycji całości.

== Imiesłowy.
IMPORTANT: Imiesłowy to nieosobowe formy czasownika!!

.Imiesłowy dzielimy na: 

- przymiotnikowe
- przysłówkowe

. *Imiesłowy przymiotnikowe* dzielą się na czynne (zakończone na -ący, -ące, -ąca, np. chorujący, mieszkającego, kochająca, leżącą) i *są tworzone od czasowników niedokonanych*.
. *Imiesłowy przymiotnikowe bierne* (zakończone na -ny, -na, -ne, -ty, -ta, -te, -ony, np. ucieszony, wyciągniętego, upiększona) i *tworzymy je od czasowników dokonanych i niedokonanych oraz od czasowników przechodnich*.

Imiesłowy przysłówkowe dzielą się na uprzednie (zakończone na -łszy, -wszy, np. odzyskawszy, spojrzawszy) i tworzymy je od czasowników dokonanych oraz imiesłowy przysłówkowe współczesne (zakończone na -ąc, np. bojąc się, pragnąc) i są tworzone od czasowników niedokonanych.

== Równoważnik zdania.
. *Równoważnik zdania* – wyraz lub ciąg wyrazowy formalnie nietworzący zdania (ponieważ nie zawiera orzeczenia).

. Przykłady:
.. Piękna pogoda.
.. Sprawa zakończona.
.. Kto tam?
.. Dokąd to?
.. Dlaczego tak?
.. Nie krzyczeć!
.. Cisza! Uwaga!
.. Nigdy więcej wojny!
.. Równoważniki zdań dzielą się na dwa zasadnicze rodzaje[:
*** Wypowiedzi, w których występują wszystkie samodzielne części mowy oprócz czasowników. Zawierają najczęściej szczegóły właśnie omawianej kwestii i występują najczęściej w dialogach: (– Czytam książkę.) – Jaką? – 1222. – Jakiego autora? – Anne Holt.
*** Wypowiedzi, w których występują czasowniki w formie nieosobowej, najczęściej imiesłowy nieodmienne.

== Pisanie.
=== Reklama.
*ŻELAZNE ZASADY:*
. Zanim zaczniesz pisać, zastanów się, czego dotyczy reklama i jakich odbiorców ma zainteresować.
(Reklama nowego rodzaju margaryny będzie skierowana raczej do kobiet prowadzących gospodarstwa domowe, owocowego żelu pod prysznic do młodych kobiet i nastolatek, zestawu klocków do młodych rodziców, ale także do dzieci!, a ekskluzywnej wody kolońskiej do bogatych mężczyzn. Język i sformułowania, jakimi się posłużysz, będą różne dla każdej z tych grup)

. Dostosuj język do grupy odbiorców.
Zawsze na początku reklamy poinformuj, jakiego produktu ona dotyczy.

. Reklama to nie informacja handlowa – musisz przede wszystkim zachęcić do kupna.

. Zastanów się, co jest największym atutem produktu, i podkreśl właśnie tę cechę.

. Postaraj się zastosować choćby część z popularnych chwytów reklamowych: dowartościowanie klienta; zasugerowanie mu, że dany produkt zwiększy jakość jego życia; podkreślenie powiązania produktu z oczekiwaniami i aspiracjami, jakie może mieć dana grupa odbiorców.

. Nie zamieszczaj żadnych informacji negatywnych!

=== Blurb.
. Z treści tej czytelnik powinien się dowiedzieć, o czym jest książka, dlaczego miałby do niej zajrzeć, a przede wszystkim dlaczego warto ją kupić.

. Jak takie informacje stworzyć i co powinny zawierać? Może to być streszczenie książki, choć trzeba wówczas uważać, by nie zdradzić zbyt wielu szczegółów ani zakończenia. Ważne też, by tekst był napisany w przystępny sposób. Może również to być opis, jakie kwestie czy problemy książka porusza – np. relacji międzyludzkich, samotności, finansów itd. Dla kogo jest przeznaczona – np. dla dzieci, dla przedsiębiorców, dla każdego, dla wymagających. Co czytelnik zyska, kupując tę książkę? Jaką wartość ta książka wniesie w jego życie? Na przykład:

. pozna proste przepisy na smaczne dania;
. nauczy się gotować;
. dozna dreszczyku emocji;
. pozna sposoby negocjacji w biznesie;
. pozna świat ludzi takich jak on i jak sobie ci ludzie poradzili w podobnej sytuacji (np. palaczy, którzy wyszli z nałogu).

=== Instrukcja.
. Pisz maksymalnie zwięźle i precyzyjnie. Masz tak poinstruować odbiorcę, aby bez zastanawiania się wiedział, co ma robić.
. Używaj bezokoliczników lub czasowników w trybie rozkazującym.
. Nie stosuj niepotrzebnych przymiotników ani ozdobników stylistycznych.
. Zadbaj o logiczną kolejność punktów instrukcji.

=== Dedykacja.
. Adresat jest niezwykle ważny. Musi być wpisany!
. Musisz się podpisać.
. Koniecznie opisz okazję (intencję), z jakiej wpisujesz dedykację. Mogą to być urodziny, imieniny, rocznica itp., możesz też coś komuś zadedykować w dowód uznania czy wdzięczności np. za pomoc w nauczeniu się matematyki.
. Pod dedykacją wpisuje się nazwę miejscowości i datę.

=== Opis sytuacji.
. Akcja opisu sytuacji dzieje się najczęściej szybko, w mgnieniu oka, dlatego opis sytuacji, w przeciwieństwie do statycznego opisu osoby czy rzeczy, jest zawsze bardzo dynamiczny. By zredagować dobry opis sytuacji, musimy wyobrazić sobie, co się dzieje, i jak najdokładniej to opisać, skupiając się na akcji, nie na opisach. Unikaj stosowania niepotrzebnych przymiotników.

. Pamiętaj o trójdzielnej kompozycji – we wstępie wprowadź do wydarzeń i zarysuj tło sytuacji. W rozwinięciu skup się na sytuacji, zaś w zakończeniu powinieneś rozwiązać akcję.

. Cechy opisu sytuacji:
.. dynamika,
.. nagromadzenie czasowników,
.. używanie przysłówków (np. szybko, nagle),
.. krótkie zdania,
.. związek przyczynowo-skutkowy,
.. jedność czasu, miejsca i akcji.

== Typy planów filmowych.
. Totalny – to ogólny obraz topografii przestrzeni akcji. Ludzka postać jest niewielka. Ten plan używany jest do ogólnych opisów miejsca akcji oraz prezentacji pleneru.

. *Ogólny* – to pełny obraz miejsca akcji. Plan służy informacji opisowej i przekazaniu ogólnych informacji miejscu, w którym znajduje się bohater. Sylwetka ludzka jest zauważalna, ale nie najważniejsza.

. *Pełny* – to wycinek planu ogólnego. Cała sylwetka ludzka (od stóp do głów) jest widoczna w kadrze. Można dostrzec też część dekoracji.

. *Amerykański* – to wycinek planu pełnego. Ludzka postać jest pokazana od kolan w górę i odgrywa rolę dominującą w kadrze. Najczęściej stosuje się ten plan do ukazania zachowań bohaterów.

. *Zbliżenie* lub wielki plan (ang. close up) – jeden z bliskich planów filmowych. Twarz człowieka lub inny obiekt zajmuje większą część kadru. Ukazuje stan psychiki i emocje postaci.

. Bliski (*półzbliżenie*) – plan służy do portretowania bohaterów. Pokazuje człowieka od popiersia w górę.

. *Detal* – plan szczegółu ciała, celem jest maksymalne skupienie uwagi na danym elemencie, obserwowanie detali. Może to być ciasny kadr oczu lub ust postaci podkreślający emocje.

== Wiedza o filmie.
=== Ważne pojęcia.

. *Reżyseria* - ogół czynności zwiazanych z wystawieniem sztuki teatralnej, realizacją filmu, audycji

. *Scenografia* – plastyczna oprawa filmu, sztuki teatralnej, widowiska operowego, baletowego lub telewizyjnego. Składa się z dekoracji, kostiumów, rekwizytów, charakteryzacji postaci i oświetlenia.

. *Montaż* jest łączeniem oddzielnych części w całość. W technice wiąże się to ze składaniem elementów w zespoły konstrukcyjne, a tych w maszyny i urządzenia. Działania montażowe realizowane są w oparciu o dokumentację techniczną.

. *Kadr*, klatka filmowa lub tylko klatka – pole obrazu tworzonego przez obiektyw, wydzielone do obserwacji w urządzeniu optycznym.

. *Ujęcie* – najmniejsza dynamiczna jednostka budulca filmowego zawarta między dwoma najbliższymi cięciami montażowymi; odcinek taśmy filmowej z obrazem filmowanym trwający od startu kamery do momentu jej zatrzymania. Należy odróżniać pojęcie ujęcia od planu.

. *Scena* – przestrzeń (podwyższenie) w budynku teatralnym przeznaczona do wystawiania utworów, usytuowana powyżej widowni i oddzielona od niej kurtyną, odpowiednio wyposażona pod względem technicznym, stanowiąca miejsce gry aktorów.

. W filmie *sekwencja* to jednostka kompozycyjna obejmująca dramaturgicznie zamknięty fragment akcji i składający się ze scen.

=== Gatunki filmowe.
. *Dramat* - czyli „działanie, akcja”) – jeden z trzech rodzajów literackich (obok liryki i epiki). Jest to właściwie rodzaj sztuki na granicy teatru i literatury. ... Jako utwór literacki dramat charakteryzuje się przede wszystkim tym, że jest tworzony w celu realizacji scenicznej.

. *Komedię* cechuje pogodny nastrój, komizm, najczęściej żywa akcja i szczęśliwe dla bohaterów zakończenie.

. *Fantastyka naukowa, SF*, odmiana literatury fantastycznej; termin określający literaturę (także film) fantastyczną, w której konstrukcję świata przedstawionego uzasadniają wyjaśnienia o charakterze naukowym lub przynajmniej mające pozory naukowości.

. *Fantasy* – gatunek literacki lub filmowy używający magicznych i innych nadprzyrodzonych form, motywów, jako pierwszorzędnego składnika fabuły, myśli przewodniej, czasu, miejsca akcji, postaci i okoliczności zdarzeń.

. *Kryminałem* określa się potocznie powieść kryminalną, której fabuła bazuje na zagadkowym przestępstwie. Bohaterami fabuły są sprawcy przestępstwa, osoby, które starają się rozwikłać zagadkę oraz osoby postronne.

. *Western* – gatunek filmu fabularnego, powieści awanturniczej albo sztuki scenicznej, obejmujący utwory, których akcja rozgrywa się w okresie kolonizacji i stabilizowania się życia na terenach zachodnich stanów USA, zwanych Dzikim Zachodem.

. *Film sensacyjny* – swoista odmiana rodzajowa (nie gatunek filmowy) filmu fabularnego, typ struktury dzieła filmowego rozwijanej i uzupełnianej przez różne gatunki filmowe, które można traktować jako odmiany filmu sensacyjnego; wyznacznikiem rodzajowym nie jest więc treść filmu, lecz sposób przedstawiania wydarzeń.

. *Film przygodowy* – film o akcji skonstruowanej z ciągu przygód protagonisty, charakteryzujący się szybkim tempem akcji, brawurowymi rozwiązaniami fabularnymi oraz licznymi przeszkodami pokonywanymi przez bohaterów.

. *Film kostiumowy* – gatunek filmów odwzorowujących daną epokę historyczną poprzez użycie charakterystycznych dla niej dekoracji i strojów; termin „film kostiumowy” odnosi się głównie do produkcji zawierających fikcyjnych bohaterów.

. *Filmy dla młodzieży* - rodzaj produkcji filmowych przeznaczonych dla widzów w okresie dorastania. Tematami przewodnimi tego typu produkcji są zazwyczaj przyjaźń, pierwsza miłość, problemy w szkole, inicjacja seksualna oraz różnego rodzaju uzależnienia.

== Cechy filmu literackiego.
. fikcja 
. przedmiot estetyczny 
. integracja języka 
. twór intertekstualny 
. twór autoteliczny