= Środowisko przyrodnicze Afryki.
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:imagesdir: obrazki
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

NOTE: *Opracowujący temat:* Wiktor

== Afryka.

=== Ogólne informacje.

. Powierzchnia Afryki wynosi 30,3 mln km^2^.
. Pod względem wielkości terytorium jest to drugi (po Azji) kontynent na świecie.
. W Afryce znajduje się największa pustynia świata - Sahara.
. Na kontynęcie Afrykańskim mieszka ponad miliard ludzi.
. Poziom rozwoju gospodarczego większości leżących tam państw jest niski.
. Leży na wszystkich czterech półkulach.
. Przez jej obszar przebiega południk 0^o^ oraz równik.
. Równik przecina Afrykę niemal w połowie.

TIP: Powierzchnia Sahary przekracza 8 mln km^2^.

== Ukształtowanie powierzchni Afryki.

. Ukształtowanie terenu uznać za wyjątkowe.
. To kontynent typowo *wyżynny*.
.. ponad 75% jego powierzchni znajduje się na wyskokości od 300 m n.p.m. do 2000 m n.p.m., a średnia wysokość wynosi 658 m n.p.m.
. *Największe wyżyny:* Abisyńska i Wschodnio-afrykańska (znajdują się one na wschodzie.).
. Wyżyny są poprzecinane *rozległymi kotlinami*, czyli obniżeniami terenu otoczonymi ze wszystkich stron przez wzniesienia.
. *Do największych kotlin należą:* Konga, Czadu oraz Kalahari.
. Najwyższe pasma górskie występują w północnej części Afryki (góry Atlas) oraz na południu (Góry Smocze i Przylądkowe).
. *Najwyższy szczyt:* Kibo (5895 m n.p.m.), położony w masywie wulkanicznym *Kilimandżaro*.
. Wzdłuż wybrzeży kontynentu ciągnie się wąski pas nizin.

== Wielkie Rowy Afrykańskie.

* W Afryce Wschodniej, od rzeki Zambezi po morze Czerwone, ciągnie sięsystem głębokich rowów tektonicznych zwanych *Wielkimi Rowami Afrykańskimi*.
** Tworzą go rozległe, dochodzące nawet do 1000 km szerokości, doliny ograniczone uskokami.
** W odrębie tych rowów występuje wiele aktywnych i wygasłych wulkanów oraz duże jeziora tektoniczne.
** Wielkie rowy afrykańskie powstały na skutek pęknięcia płyty litosfery (na której jest położona Afryka) na dwie części. Ten proces rozpoczął się kilkadziesiąt milionów lat temu.

== Czynniki wpływające na klimat Afryki.

* Na klimat Afryki największy wpływ ma *położenie geograficzne*.
* *Kontyneny ten leży po obu stronach równika*, dzięki czemu strefy klimatyczne *układają się symetrycznie*.
