= Gramatyka (tematy: 4.2-4.3)
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:stem:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Rodzaje szyków zdań w języku niemieckim.

====
W języku niemieckim wyróżnia się trzy rodzaje szyku zdania: *prosty*, *przestawny* i *końcowy*. Szyk prosty to szyk, w którym *na pierwszym miejscu w zdaniu jest podmiot* (osoba) *, a na drugim orzeczenie* (czasownik). Szyk przestawny to *odwrotność szyku prostego*, czyli najpierw *orzeczenie, a potem podmiot*. Szyk końcowy oznacza, że *czasownik stoi na końcu zdania*.
====

== Obwohl
Spójnik *_obwohl* (_chociaż, mimo że_) rozpoczyna zdanie okolicznikowe przyzwolenia w zdaniach tgo typu występuje *szyk końowy*.

* Mia hat den Chemietest mitgeschrieben, *obwohl* sie krank *war*.

NITE: Jeżeli zdanie poboczne występuje jako pierwsze, w zdaniu głównym stosujemy *szyk przestawny*.

* *Obwohl* Mia krank *war*, *hat* sie den Chemietest *mitgeschriebien*.

== Deshalb i trotzdem

W zdaniach z *deshalb* (_dlatego_) i trotzdem (_mimo to_) stosujemy *szyk przestawny*.

* Ich möchte fit bleiben, *deshalb* mache ich Sport.

* Er hat viel gelernt, *trotzdem* hat er eine Sechs bekommen.
