= Chiny, najludniejsze państwo świata.
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:imagesdir: obrazki
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Ogólna charakterystyka.
. *powierzchnia:* 9,3 km^2^
. *stolica:* Pekin
. *waluta:* yuan
. *język:* chiński

NOTE: Chiny są trzecim krajem pod względem wielkości, po Rosji i Kanadzie. 3/4 powierzchni całego kraju to wyżyny i góry (głównie w zachodniej części kraju). We wschodniej części kraju dominują niziny (klimat monsunowy). W zachodniej, północnej części kraju przy niewielkich opadach dominują pustynie i stepy.

== Zaludnienie.
* *ludność:* 1,4 bilionów (2019)
* Pod koniec lat 70tych wprowadzono program kontroli urodzeń (polityka jednego dziecka).
* Przyrost naturalny wynosi 4‰ (w latach 70tych ok 30‰).
** Przewaga liczby mężczyzn w społeczeństwie.
** Szybkie starzenie się społeczeństwa.
** 95% ludności mieszka we wschodnich regionach.
** Gęstość zaludnienia *na północy Chin:* 500 os/km^2^, we wschodnich regionach 5 os/1 km^2^.

== Gospodarka.
