= Indie, państwo kontrastów społecznych i gospodarczych.
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:imagesdir: obrazki
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Problemy demograficzne..
. Pod względem ludności Indie są drugim (po Chinach) państwem świata. W tym kraju żyje 18% mieszkańców Ziemi. Wskaźnik przyrostu naturalnego od wielu lat utrzymuje się powyżej 10‰. Liczba ludności szybko wzrasta. O 150 mln osób w każdej kolejnej dekadzie.
. Niekontrlowany wzrost liczby mieszkańców przyczynia się do powstania i rozwoju slamsów.
. Na ulicach można spotkać zarówno biednych, jak i mieszkających w pałacach. Wynika to z systemu kastowego.

NOTE: Charakterystyczne dla społeczeństwa Indii jest zróżnicowanie religijne oraz ogromna różnorodność etniczna i językowa 

== Kontrasty indyjskiej edukacji.
* W praktyce ok. 350 mln mieszkańców (25% społeczeństa) to analfabeci.
* Każdego roku uczelnie opuszcza ok. 2,5 miliona doskonale wykształconych absolwentów.

== Rozwój indyjskiej gospodarki.
. Ogromny rynek zbytu, ok 45% mieszkańców, ma niej niż 25 lat.
. Rosnąca liczb rąk do pracy zachęca przedsiębiorców do inwestowania w tym kraju.
. Tania, wykształcona, anglojęzyczna kadra pracownicza. Dzięki niej może się rozwijać sektor nowoczesnych usług.
. Reformy gospodarcze rozpoczęły się w latach 90-tych XX wieku. Polegały one między innymi na prywatyzacji i wprowadzeniu ułatwień podatkowych dla firm zagranicznych.

== Indyjskie rolnictwo.
*Zielona rewolucja* (lata 60-te XX wieku). Wprowadzono bardziej wydajne rodzaje ryżu i pszenicy.

TIP: Indie są czołowym producentem i eksporterem wielu artykułów rolnych.

== Rosnące znaczenie przemysłu.
. Największymi działaniami przetwórstwa przemysłowego w Indiach są:
.. *Produkcje:* odzieży, wyrobów tekstylnych, skórzanych oraz artykułów sporzywczych i napojów.
.. Główne ośrodki produkcji powstały w dużych miastach: Mumbaju, Kolkaty, Delhi, Hajdarabadu.
.. Produkcja środków transportu.
.. Produkcja metali i wyrobów ze stali.
