= Podstawy HTML, kurs (Wiktor Grabowski Id LO)
:toc:
:toc-title: Spis treści
:sectnums:
:icons: font
:stem:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Informacje ogólne
NOTE: Krótko o HTML.

HTML (HyperText Markup Language) jest językiem znaczników używanym do tworzenia struktur i prezentacji stron internetowych. HTML definiuje strukturę semantyczną zawartości strony, która składa się z różnych elementów, takich jak nagłówki, akapity, linki, obrazy, tabele itp. Przeglądarki internetowe interpretują kod HTML i wyświetlają go w formie graficznej dla użytkownika.

Aby używać HTML, wystarczy otworzyć plik tekstowy w edytorze kodu i zacząć pisać kod HTML. Kod HTML składa się z zestawu znaczników, które określają strukturę i formatowanie różnych elementów strony. Każdy znacznik HTML zaczyna się od znaku "<" i kończy się znakiem ">". Na przykład, <h1> to znacznik nagłówka pierwszego poziomu, <p> to znacznik paragrafu, <a> to znacznik linku, itd.

=== Podstawowa struktura dokumentu.

----
<!DOCTYPE html>
<html>
  <head>
    <title>Tytuł Twojej strony</title>
  </head>
  <body>
    Treść Twojej strony.
  </body>
</html>
----

== Pisanie językiem HTML

=== Znaczniki w HTMLu.

. <h1> do <h6> (Nagłówki):
Służą do oznaczania nagłówków na stronie. <h1> to najważniejszy nagłówek, a <h6> to najmniej istotny. Nagłówki są używane do hierarchicznego organizowania treści i nadawania im znaczenia.

. <p> (Paragraf):
Używany do oznaczania akapitów tekstu. Wykorzystywany do strukturyzowania i formatowania treści tekstowych.

. <a> (Link):
Służy do tworzenia hiperłączy (linków) do innych stron internetowych, dokumentów lub lokalizacji na tej samej stronie. Atrybut href określa adres URL docelowej strony.

. <img> (Obrazek):
Umożliwia wstawienie obrazka na stronie. Atrybut src określa ścieżkę do obrazka, a alt zapewnia tekst zastępczy, który jest wyświetlany, gdy obrazek nie może być załadowany.

. <ul> (Lista nieuporządkowana):
Służy do tworzenia listy nieuporządkowanej, gdzie elementy nie mają określonego porządku. Każdy element listy jest zazwyczaj oznaczony kropką, kółkiem lub innym symbolem.

. <ol> (Lista uporządkowana):
Umożliwia tworzenie listy uporządkowanej, w której elementy są numerowane lub zastosowana jest inna sekwencja znaków oznaczająca porządek.

. <table> (Tabela):
Służy do tworzenia tabel. Składa się z <table>, <thead>, <tbody>, <tr>, <th> i <td>. Pozwala na organizowanie danych w wiersze i kolumny, przydaje się do prezentacji informacji w sposób uporządkowany.

. <form> (Formularz):
Używany do tworzenia formularzy, które pozwalają użytkownikom wprowadzać dane. Atrybuty action i method określają adres URL, do którego zostaną przesłane dane formularza oraz metoda wysyłki tych danych (np. POST lub GET).

. <div> (Pojemnik):
Jest to kontener lub pojemnik, który służy do grupowania elementów na stronie. Często używany do stylizacji i zarządzania układem strony.

. Komentarze:

* "// treść komentarza" (wielolinijkowy):

----
/* To jest komentarz wielolinijkowy
   który rozciąga się na kilka linii */
----
* Oraz komentarz jednolinijkowy
** "/* treść komentarza */"
----
// To jest komentarz jednolinijkowy
----



TIP: *Wymienione z naczniki to tylko niektóre z podstawowych znaczników HTMLu, których jest bardzo dużo.*
